spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/db_sellwatches"
    username: "root"
    password:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: true
    database-platform: "org.hibernate.dialect.MySQL8Dialect"
jwt:
  signerKey: "1Du6BPWxW3ZPFIJv/RuhcPnLuWUtsDnpw8lgrBH14kOueF5FPtrstwD4it8RPIag"